name: Docker CI/CD Workflow

on:
  push:
    branches:
      - docker_ci

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.image-tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn joblib

      - name: Train model
        run: python scripts/train.py

      - id: set-image-tag
        name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/mlops_assignment3:latest
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build -t $IMAGE_TAG .

      - name: Run Docker container and verify predictions
        run: docker run --rm ${{ steps.set-image-tag.outputs.image-tag }} python scripts/predict.py

      - name: Show built image tag output
        run: echo "Built image tag is ${{ steps.set-image-tag.outputs.image-tag }}"

  push_image:
    needs: build_and_test_container
    runs-on: ubuntu-latest
    env: 
        IMAGE_TAG: ${{ needs.build_and_test_container.outputs.image-tag }}

    steps:
      - name: Show image tag from previous job
        run: |
                echo "Image tag received from build job: ${{ needs.build_and_test_container.outputs.image-tag }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ needs.build_and_test_container.outputs.image-tag }}
